- name: Install laptop only packages
  become: true
  pacman:
    name:
      - amd-ucode
      - brightnessctl
      - linux-firmware
      - dmidecode
      - fwupd
  tags:
    - never
    - laptop


- name: Enable Hardware Services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - bluetooth
  tags:
    - never
    - laptop

- name: Ensure logind drop-in directory exists
  become: true
  file:
    path: /etc/systemd/logind.conf.d
    state: directory
    mode: '0755'
  tags:
    - never
    - laptop

- name: Configure clamshell mode
  become: true
  copy:
    dest: /etc/systemd/logind.conf.d/clamshell.conf
    mode: '0644'
    content: |
      [Login]
      HandleLidSwitch=ignore
      HandleLidSwitchDocked=ignore
      HandleLidSwitchExternalPower=ignore
  tags:
    - never
    - laptop
