- name: Setup dev tools
  become: true
  pacman: 
    name:
      - tmux
      - rsync
      - man-db
      - less
      - tldr
      - ripgrep
      - fd
      - git
      - bat
      - npm
      - pnpm
      - btop
      - eza
      - unzip
      - wget
      - obsidian
      - fastfetch
    state: present
  tags:
    - install
    - tools
